version: '3.4'

services:

  local-keycloak:
    image: quay.io/keycloak/keycloak:latest
    container_name: local-keycloak
    hostname: localhost:3000
    ports:
      - "8080:8080"
    environment:
      - KC_BOOTSTRAP_ADMIN_USERNAME=admin
      - KC_BOOTSTRAP_ADMIN_PASSWORD=password
    networks:
      - local
    command: [ "start-dev" ]
  

networks:
    local: