version: '3.4'

# Note: Need to self sign a certificate and add it to trusted root to use local keycloak. See Readme.

services:

  local-keycloak:
    image: quay.io/keycloak/keycloak:latest
    container_name: local-keycloak
    ports:
      - "8443:8443"
    environment:
      - KC_BOOTSTRAP_ADMIN_USERNAME=admin
      - KC_BOOTSTRAP_ADMIN_PASSWORD=password
      - KC_HOSTNAME=localhost
      - KC_HOSTNAME_PORT=8443
      - KC_HTTPS_CERTIFICATE_FILE=/opt/keycloak/conf/server.crt
      - KC_HTTPS_CERTIFICATE_KEY_FILE=/opt/keycloak/conf/server.key
    volumes:
      - ./ssl3/local.keycloak.crt:/opt/keycloak/conf/server.crt
      - ./ssl3/local.keycloak.key:/opt/keycloak/conf/server.key
    networks:
      - local
    command: [ "start-dev" ]
  

networks:
    local: