version: '3.4'

services:

  local-postgres:
    image: dpage/pgadmin4
    container_name: local-pgadmin
    ports:
      - 5434:80
    environment:
      - PGADMIN_DEFAULT_EMAIL=user@local.com
      - PGADMIN_DEFAULT_PASSWORD=password
    networks:
      - local

networks:
    local: