version: '3.4'

services:

  local-postgres:
    image: postgres
    container_name: local-postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: password
    ports:
      - 5432:5432
    networks:
      - local

  local-pgadmin:
    image: dpage/pgadmin4
    container_name: local-pgadmin
    ports:
      - 5434:80
    environment:
      - PGADMIN_DEFAULT_EMAIL=user@local.com
      - PGADMIN_DEFAULT_PASSWORD=password
    networks:
      - local

networks:
    local: