version: '3.4'

services:

  local-wiremock:
    image: sheyenrath/wiremock.net
    container_name: local-wiremock
    ports:
      - "8443:80"
    environment:
      # TODO: Fix the Https issue
      - UseSSL=true
      - Port=8443
    networks:
      - local

networks:
    local: